name: planetsportss
description: App deportiva creada por Thiago

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.7
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.2
  image_picker: ^1.0.5
  url_launcher: ^6.3.1
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
